### ISSUE TITLE
"Prazo adicional de envio" não está sendo somado ao prazo total de envio

### ISSUE THREAD

**Issue by ivanaugustobd** [freterapido/freterapido_magento#39]
Mesmo após configurar o "Prazo adicional de envio/postagem (dias)" (para 30, para ser mais específico), o checkout continua exibindo os prazos originais, sem a adição do valor configurado no admin (continua exibindo 7~10 dias de prazo). 
Erro persiste mesmo limpando o cache/reindexando todos os índices..

**Comment by ivanaugustobd** [comment]
Encontrei algo que pode ser relevante:
No arquivos _app/code/community/Freterapido/Freterapido/Model/Carrier/Freterapido.php_, no método `_getQuoteApi()`, o valor do "prazo_adicional" chega corretamente pelo `$this->_leadtime`; porém ao debugar a `$response` (decodificada) um pouco abaixo, os "prazo_entrega" retornam com os valores mencionados acima, sem a adição do prazo adicional (que aparentemente foi envido corretamente).
Poderia ser isso algum erro na API que recebe essa requisição e faz as estimativas? :thinking:

**Comment by ivanaugustobd** [comment]
Opa, um workaround para este problema:
Após o `$this->_carriers = isset($response->transportadoras) ? $response->transportadoras : [];`, adicionar 

```
$this->_carriers = array_map(function ($carrier) {
    $carrier->prazo_entrega = $carrier->prazo_entrega + $this->_leadtime;

    return $carrier;
}, $this->_carriers);
```

Reestrutura os resultados com valores corretos :grimacing:

**Comment by davidalves1** [comment]
Opa, beleza @ivanaugustobd?
Essa funcionalidade foi removida do módulo, pois implementamos as regras de frete que podem ser configuradas diretamente no [painel Frete Rápido](https://freterapido.com/painel) no menu **Regras de Frete** e, como bem observou, esse valor poderia ser aplicado 2 vezes. Pode ser que a sua extensão esteja desatualizada, por isso ainda aparece a opção na configuração.
Qualquer dúvida estamos a disposição.

**Comment by ivanaugustobd** [comment]
De fato, estávamos usando uma versão mais antiga. Fizemos a atualização e correu tudo bem.
Muito obrigado pelos esclarecimentos e agilidade na resposta! :D
