### ISSUE TITLE
Módulo tentando contratar frete mesmo não sendo ele o método de entrega

### ISSUE THREAD

**Issue by ivanaugustobd** [freterapido/freterapido_magento#41]
Ao tentar fazer o envio de pedidos que **não** foram feitos tendo o Frete Rápido como forma de entrega, acusa a mensage de erro:

> Frete Rápido - Não foi possível realizar a contratação do frete. Motivo: Erro ao tentar se comunicar com a API - Code: 422. Error: {"destinatario.endereco.cep":["The selected destinatario.endereco.cep is invalid."]}

Print do erro: http://cdn.imgpaste.net/2017/12/01/CI6uX.png
Se o módulo do Frete Rápido é desativado, conseguimos fazer o envio desses pedidos..

Como proceder?

Grato desde já! :D

**Comment by ivanaugustobd** [comment]
Detalhes adicionais:

Versão do Magento: 1.9.3.2
Versão do módulo: 1.2.0 (versão do branch master nesse repo)

**Comment by dev-freterapido** [comment]
Bom dia @ivanaugustobd 

Para qualquer tratativa de suporte ao Frete Rápido, pedimos que seja utilizado o canal de contato via Slack (https://fr-slack.herokuapp.com/). Nele temos um canal especializado de suporte a desenvolvimento e integração.

**Comment by ivanaugustobd** [comment]
Ok, obrigado!
